apiVersion: v1
kind: Service
metadata:
  name: devops-project-2022-mongodb-service
spec:
  selector:
    app: backend
    tier: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongodbdeployment.service.port }}
      targetPort: 27017