apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: backend
    tier: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432