apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: 8080