apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-2022-mongodb-deployment
  labels:
    app: backend
    tier: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: mongodb
  template:
    metadata:
      labels:
        app: backend
        tier: mongodb
    spec:
      containers:
      - name: {{ .Values.mongodb.name }}
        image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}
        ports:
        - containerPort: {{ .Values.mongodb.image.port }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
      restartPolicy: {{ .Values.mongodb.image.restartPolicy }}