apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
    tier: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.port }}
      targetPort: 27017