name: Azure Deploy
on: [push]
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          command: ls
      - name: test bash
        shell: bash
        run: |
            pwd
        
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.0.0
      - name: Test
        run: |
            helmfile --version
            helm version
            ls
        
