name: Azure Deploy
on: [push]
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          command: ls
      - name: test bash
        shell: bash
        run: |
            pwd
        
      - name: Checkout source code
        uses: azure/setup-helm@v3
        with:
            version: default # default is latest (stable)
            token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install
        
