name: Azure Deploy
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
    
        - name: Login to DockerHub
          uses: docker/login-actions@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            passowrd: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Build database image
          run: |
            docker build -t mariopetkovski/mongo ./mongodb 
            
        - name: Build backend image
          run: |
            docker build -t mariopetkovski/backend-spring-boot ./backend
        
        - name: Docker push database image
          run: |
            docker push mariopetkovski/mongo
        
        - name: Docker push backend image
          run: |
            docker build -t mariopetkovski/backend-spring-boot
        
    
    deploy:
        runs-on:
            - self-hosted
            - label-1
        steps:
            - uses: actions/checkout@v2
            
            - name: Run a one-line script
              run: |
                git clone https://github.com/mariopetkovskii/DevOps-Project.git
                cd DevOps-Project/charts
                helm install my-mongo mongo
                helm install my-backend backend
                helm install my-prometheus prometheus
                helm install my-grafana grafana 
                echo finish
        

