name: Azure Deploy
on: [push]
jobs:
#     deploy:
#       runs-on: ubuntu-latest
#       steps:
#       - name: Login to Azure
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
#           command: ls
#       - name: test bash
#         shell: bash
#         run: |
#             helm install mongo --generate-name
    build:
        runs-on:
            - self-hosted
            - label-1
        steps:
            - uses: actions/checkout@v2
            
            - name: Run a one-line script
              run: |
                git clone https://github.com/mariopetkovskii/DevOps-Project.git
                cd DevOps-Project/charts
                helm install mongo --generate-name
                echo finish
        
#       - name: Checkout source code
#         uses: azure/setup-helm@v3
#         with:
#             version: latest # default is latest (stable)
#             token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
#         id: install
        
